version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: matheus/nginx
    container_name: nginx
    ports:
      - "80:80"
    network:
      - production-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    network:
      - production-network
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context .
    image: matheus/alura
    container_name: alura-book1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context .
    image: matheus/alura
    container_name: alura-book2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

 node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context .
    image: matheus/alura
    container_name: alura-book3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"


networks:
  production-network:
    driver: bridge

